config/routes.rb
Rails.application.routes.draw do
   resources :category_records
   resources :records
   resources :categories

  devise_for :users
  devise_scope :user do
    authenticated :user do
      root 'categories#index', as: :authenticated_root
    end
    unauthenticated do
      root 'splash#index', as: :unauthenticated_root
    end
    get '/users/sign_out' => 'devise/sessions#destroy'
  resources :users, only: [:index]
  end
  resources :categories do 
    # resources :records, except: [:index]
    resources :records
  end
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :category_records, dependent: :delete_all
  has_many :records, through: :category_records, dependent: :delete_all
  has_one_attached :image

  validates :name, presence: true
  validates :user, presence: true

  def total_amount
    records.sum('amount')
  end

  def recent_transactions
    records.order(created_at: :desc)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show edit update destroy]
  before_action :authenticate_user!
  load_and_authorize_resource

  # GET /categories or /categories.json
  def index
    @categories = current_user.categories
  end

  # GET /categories/1 or /categories/1.json
  def show
    # @category = set_category
    @category = Category.find(params[:id])
    @records = @category.records.order(created_at: :desc)
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit; end

  # POST /categories or /categories.json
  def create
    @category = current_user.categories.new(category_params)

    respond_to do |format|
      if @category.save
        # format.html { redirect_to category_url(@category), notice: 'Category was successfully created.' }
        format.html { redirect_to categories_path, notice: 'Category was successfully created.' }

      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: 'Category was successfully updated.' }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:name, :image)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<article class="category d-flex" id="<%= dom_id category %>">
  <div class="image">
    <%= image_tag(category.image) %>
  </div>
  <div class="name-date d-flex">
    <h3 class="name"><%= category.name %></h3>
    <p class="date d-flex"> <%= category.created_at.strftime('%d %b %Y') %></p>
  </div>
  <p class="total-amount">$<%=category.total_amount%></p>

</article>

app/views/categories/_form.html.erb
<%= form_with(model: category, id: "save-categ-from") do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being Budgyd:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input">
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, required: true, placeholder: "Name" %>
  </div>
  <strong>Upload an image...</strong>
  <div class="input choose">
    <%= form.label :image, style: "display: none" %>
    <%= form.file_field :image, required: true, class:"input-file"%>
  </div>
    
  <div class="d-flex">
    <div class="submit">
      <% form.submit 'Save' %>
    </div>
  </div>
<% end %>

app/views/categories/edit.html.erb
<nav class="header-categories d-flex flex-center">
  <div class="icons">
    <%= link_to  category_path(@category) do %>
      <i class="fa-solid fa-arrow-left back"></i>
    <% end %>
  </div>
  <h1 class="transaction-header-nav">EDITING CATEGORY</h1>
  <div class="actions-save">
    <input type="submit" name="commit" value="save" class="login-button new-edit-cat" form="save-categ-from" data-disable-with="Log in">
  </div>
</nav>

<%= render "form", category: @category %>

<br>

<div>
  <% link_to "Back to categories", categories_path %>
</div>
<br>
 

app/views/categories/index.html.erb
<nav class="header-categories d-flex flex-center">
  <%= link_to  destroy_user_session_path, class: "icons" do%>
    <i class="fa-solid fa-right-from-bracket"></i>
  <% end %>
    <h1>CATEGORIES</h1>
</nav>

<p style="color: green"><%= notice %></p>

<div class="categories">

  <% if @categories == [] %>
    <article class="category">
      <p>No Category has been created yet !!!</p>
    </article>
  <% end %>

  <% @categories.each do |category| %>
    <%= link_to category do %>
      <%= render category %>
    <%end%>
  <% end %>
</div>

<div class="new-cat-btn">
  <button>
    <%= link_to "New category", new_category_path %>
  </button> 
</div>

app/views/categories/new.html.erb
<nav class="header-categories d-flex flex-center">
  <div class="icons">
    <%= link_to  categories_path do %>
      <i class="fa-solid fa-arrow-left back"></i>
    <% end %>
  </div>
  <h1 class="transaction-header-nav">NEW CATEGORY</h1>
  <div class="actions-save">
    <input type="submit" name="commit" value="save" class="login-button new-edit-cat" form="save-categ-from" data-disable-with="Log in">
  </div>
</nav>

<%= render "form", class:"category-form", category: @category %>

<br>

app/views/categories/show.html.erb
<% render @category %>

<nav class="header-categories d-flex flex-center">
  <div class="icons">
    <%= link_to  categories_path do %>
      <i class="fa-solid fa-arrow-left back"></i>
    <% end %>
  </div>
  <h1>CATEGORY DETAILS</h1>
</nav>

<p style="color: green"><%= notice %></p>

<article class="category transaction">
  <div class="category-head d-flex">
    <div class="image">
      <%= image_tag(@category.image) %>
    </div>
    <div class="name-date d-flex">
      <h3 class="name"><%= @category.name %></h3>
    </div>
    <p class="total-amount">$<%=@category.total_amount%></p>
    <div class="btn-changes d-flex flex-center">
      <div class="actions-btn">
        <%= link_to "Edit", edit_category_path(@category) %>
      </div>
      <div class="delete-btn">
        <%= button_to "DESTROY", @category, class:"delete", method: :delete %>
      </div>
    </div>
  </div>
  <br>
  <hr class="line-bar">
  <p class="date d-flex"> <%= @category.created_at.strftime('%Y') %>
     <span>_<%= @category.created_at.to_formatted_s(:short) %></span>
  </p>
  <div class="total-payment d-flex flex-center">
    <p class="">TOTAL PAYMENT</p>
    <p class="total-amount">Tolal: $<%=@category.total_amount%></p>
  </div>
  <br>
  <hr>

  <div class="transactions d-flex"> 
    <h2>List of transaction </h2>
    <ul class="categoies-records">
      <% if @records == [] %>
        <br>
        <p>No Transaction made yet !!!</p>
      <% end %>

      <% @category.recent_transactions.each do |record| %>
        <%= link_to  category_record_path(@category, record) do %>
          <li id="category-record">
            <%= render 'records/record',  record: record %>
          </li>
        <%end%>
      <%end%>
    </ul>

    <div class="action-btn">
      <%= link_to "Add transaction", new_category_record_path(@category.id), class: ""%>
    </div>
  </div>

  <h2> <% @category.records.map{|record| record} %> </h2>

</article>